title: ChelOverboard
email: cheloverboard@gmail.com
description:  Download Simulation MODs Free Everyday | Join a Community - cheloverboard.com . Welcome to ChelOverboard , Here we specialize on giving Our Users High-Quality MODs that are 100% Working , Follow our Website, Youtube, and Discord Community Today!.# this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cheloverboard.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  Chel-Ash

collections:
  authors:
    output: true

    
permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: assets/css

gems: [jekyll-paginate-v2]
pagination:
  enabled: true
  collections: "posts"
  debug: false
  per_page: 9
  trail:
    before: 2
    after: 2
  sort_reverse: true
  paginate_path: "/mods-blog/page:num"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-gzip

gzip:
 extensions:
   - '.html'
   - '.css'
   - '.js'
   - '.xml'
   - '.md'
   - '.scss'
   - '.webp'