collections:
  authors:
    output: true

permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
sass:
  sass_dir: assets/css

url: "https://cheloverboard.netlify.app"

gems: [jekyll-paginate-v2]
pagination:
  enabled: true
  collections: "posts"
  debug: false
  per_page: 9
  trail:
    before: 2
    after: 2
  sort_reverse: true
  paginate_path: "/mods-blog/page:num"

plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
