[[plugins]]
  package = 'netlify-plugin-algolia-index'
    # all inputs is optional, we just show you the defaults below
    [plugins.inputs]
    exclude = ['''^\/about.*''', '''^\/mods-blog.*''', '''^\/connect.*''', '''^\/privacy.*''', '''^\/animecomics.*''', '''^\/staff.*''', '''^\/downloads.*''', '/404.html'] # don't #index this file
    # indexName = searchIndex